# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Transpiler
description: > # this means to ignore newlines until "baseurl:"
  Journey through programming language applications and software development in general.
baseurl: "" # the subpath of your site, e.g. /blog
url: "htt://blog.dhananjaya.me" # the base hostname & protocol for your site
twitter_username: rdhananjaya
github_username:  rdhananjaya

# Build settings
markdown: kramdown

gems:
 - jekyll-gist
 - jekyll-sitemap